[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ctdfjorder"
version = "0.2.4"
description = "A package for processing and analyzing CTD data."
readme = "README.md"
authors = [
    {name = "Nikolas Yanek-Chrones", email = "research@icarai.io"}
]
license = {text = "MIT License"}
requires-python = ">=3.11"
keywords = ["CTD"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "tensorflow ~=2.17.0",
    "polars ~=1.1.0",
    "psutil ~=6.0.0",
    "enlighten ~=1.12.4",
    "pandas ~=2.2.2",
    "setuptools ~=70.3.0",
    "openpyxl ~=3.1.4",
    "numpy ~=1.26.4",
    "gsw ~=3.6.18",
    "matplotlib ~=3.9.1",
    "statsmodels ~=0.14.2",
    "keras ~=3.4.1",
    "scikit-learn ~=1.5.1",
    "pyrsktools ==0.1.9",
    "colorlog ~=6.8.2",
    "pyarrow ~=17.0.0",
    "fastexcel ~=0.10.4"
]

[project.urls]
Homepage = "https://github.com/nikothomas/ctdfjorder"
Issues = "https://github.com/nikothomas/ctdfjorder/issues"

[project.scripts]
ctdfjorder-cli = "ctdfjorder.ctdfjorder:_main"

[tool.setuptools]
py-modules = ["ctdfjorder"]