name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [main] # branch to trigger deployment

jobs:
  pages:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - name: Install theme
      run: sudo pip3 install pydata-sphinx-theme
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        python-version: 3.11
